In [7]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pathlib

import tensorflow as tf


print(tf.__version__)

data_dir = pathlib.Path("./data/train")


2.3.0


In [8]:
list_ds = tf.data.Dataset.list_files(str(data_dir/'*/*'))
class_names = np.array(sorted([dir1 for dir1 in os.listdir(data_dir)]))
x=list_ds.take(3)
list(x.as_numpy_iterator())

#class_names

[b'data\\train\\swift\\n34t9dws2x9j2-IN.jpg',
 b'data\\train\\wagonr\\tbxjtnx9c4bv3-IN.jpg',
 b'data\\train\\wagonr\\otz5e72830h12-IN.jpg']

In [12]:
x=train_ds.take(3)
#list(x.as_numpy_iterator())

for i in x.as_numpy_iterator():
    print(i)

(array([[[0.7246878 , 0.57174665, 0.44233486],
        [0.72289836, 0.56995726, 0.44054544],
        [0.7170197 , 0.56407845, 0.4346667 ],
        ...,
        [0.70422673, 0.55912864, 0.4532463 ],
        [0.70333266, 0.55823463, 0.45235226],
        [0.70903504, 0.56393695, 0.4580546 ]],

       [[0.68977845, 0.5368373 , 0.40804827],
        [0.68977845, 0.5368373 , 0.41136962],
        [0.6913353 , 0.5383941 , 0.41209596],
        ...,
        [0.6958709 , 0.5538864 , 0.44644725],
        [0.68703604, 0.545882  , 0.43802762],
        [0.6909375 , 0.5464623 , 0.44026852]],

       [[0.7153325 , 0.5623913 , 0.44797784],
        [0.7197503 , 0.5668091 , 0.45283598],
        [0.7224114 , 0.5694703 , 0.45538703],
        ...,
        [0.68196666, 0.54845446, 0.43865052],
        [0.6815362 , 0.54807913, 0.43827516],
        [0.6964309 , 0.56275356, 0.45294964]],

       ...,

       [[0.44751638, 0.56550735, 0.7605541 ],
        [0.44751638, 0.56528723, 0.7609943 ],
        [0.45130533, 

In [10]:
#data augmentation function
IMG_WIDTH=224
IMG_HEIGHT=224
def decode_img(img):
  img = tf.image.decode_jpeg(img, channels=3)
  img = tf.image.convert_image_dtype(img, tf.float32) 
  img = tf.image.resize(img, [IMG_WIDTH, IMG_HEIGHT]) 
  img = tf.image.random_flip_left_right(img)
  img = tf.image.random_flip_up_down(img)
  img = tf.image.random_brightness(img, 0.3)
  return img

def get_label(path):
  part_list = tf.strings.split(path, os.path.sep)
  return part_list[-2]

def process_path(file_path):
  img = tf.io.read_file(file_path)
  img = decode_img(img)
  label = get_label(file_path)
  return img, label

In [11]:
AUTOTUNE = tf.data.experimental.AUTOTUNE
num_threads = 5 
train_ds = list_ds.map(process_path, num_parallel_calls=AUTOTUNE)

for image, label in train_ds.take(1):
  print("Image shape: ", image.numpy().shape)
  print("Label: ", label.numpy())

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Image shape:  (224, 224, 3)
Label:  b'swift'


In [70]:

train_ds = train_ds.cache()
train_ds = train_ds.shuffle(10000)
train_ds = train_ds.repeat(23)
train_ds = train_ds.batch(128)
train_ds = train_ds.prefetch(tf.data.experimental.AUTOTUNE)

In [71]:
for image, label in train_ds:
  print("Image shape: ", label)


Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagon

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagon

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wago

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'w

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' 

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wa

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr'

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b's

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'

 b'swift'], shape=(128,), dtype=string)
Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' 

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' 

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'w

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift'

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swi

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'sw

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swi

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'w

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' 

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wa

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wago

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swif

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wa

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'w

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swi

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagon

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'w

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'w

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' 

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b's

In [72]:
ds = train_ds.take(1)

In [79]:
list(ds.as_numpy_iterator())

[(array([[[[ 0.788908  ,  0.73400605,  0.68302566],
           [ 0.7933899 ,  0.73848796,  0.68750757],
           [ 0.7796644 ,  0.72476244,  0.6737821 ],
           ...,
           [ 0.7642581 ,  0.728964  ,  0.6701405 ],
           [ 0.77378196,  0.7411489 ,  0.68764746],
           [ 0.7833057 ,  0.75193316,  0.70095277]],
  
          [[ 0.788908  ,  0.73400605,  0.68302566],
           [ 0.7933899 ,  0.73848796,  0.68750757],
           [ 0.7796644 ,  0.72476244,  0.6737821 ],
           ...,
           [ 0.7676545 ,  0.73236036,  0.6698979 ],
           [ 0.7748736 ,  0.7399359 ,  0.68182516],
           [ 0.7833057 ,  0.7455043 ,  0.6968286 ]],
  
          [[ 0.788908  ,  0.73400605,  0.68302566],
           [ 0.7933899 ,  0.73848796,  0.68750757],
           [ 0.7796644 ,  0.72476244,  0.6737821 ],
           ...,
           [ 0.77427214,  0.7298393 ,  0.66986036],
           [ 0.7811349 ,  0.7367021 ,  0.6809248 ],
           [ 0.7866784 ,  0.74146396,  0.6880313 ]],
  
    

In [78]:
for image,label in ds:  # example is `{'image': tf.Tensor, 'label': tf.Tensor}`
  print(image.shape, label)

(128, 224, 224, 3) tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wa

In [81]:
# Classifiers
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
# Metrics
from sklearn.metrics import precision_recall_fscore_support

In [2]:
import tensorflow as tf
import datetime

!rm -rf ./logs/

%load_ext tensorboard


mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

In [3]:
model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(x=x_train, 
          y=y_train, 
          epochs=5, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])

Epoch 1/5
   1/1875 [..............................] - ETA: 0s - loss: 2.5340 - accuracy: 0.0312WARNING:tensorflow:From C:\Users\luke\.conda\envs\tf-gpu\lib\site-packages\tensorflow\python\ops\summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2199 - accuracy: 0.9349 - val_loss: 0.1048 - val_accuracy: 0.9690
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0962 - accuracy: 0.9708 - val_loss: 0.0801 - val_accuracy: 0.9749
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0697 - accuracy: 0.9783 - val_loss: 0.0697 - val_accuracy: 0.9775
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0529 - accuracy: 0.9833 - val_loss: 0.0661 - val_accuracy: 0.9788
Epoch 5/5
1875/1875 [==============================]

In [5]:
%tensorboard --logdir logs/fit


Reusing TensorBoard on port 6006 (pid 164724), started 0:04:16 ago. (Use '!kill 164724' to kill it.)

In [ ]:
!kill 164724