In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pathlib

import tensorflow as tf


print(tf.__version__)

data_dir = pathlib.Path("./data/train")


2.3.0


In [52]:
list_ds = tf.data.Dataset.list_files(str(data_dir/'*/*'))
class_names = np.array(sorted([dir1 for dir1 in os.listdir(data_dir)]))
x=list_ds.take(3)
list(x.as_numpy_iterator())

#class_names

b'data\\train\\wagonr\\8s6u4j94w5pi3-IN.jpg'
b'data\\train\\wagonr\\dozxw6e55vhm1-IN.jpg'
b'data\\train\\wagonr\\2iub1dkyad3-IN.jpg'


In [53]:
x=train_ds.take(3)
#list(x.as_numpy_iterator())

for i in x.as_numpy_iterator():
    print(i)

InvalidArgumentError: slice index -1 of dimension 0 out of bounds.
	 [[{{node strided_slice}}]]

In [63]:
#data augmentation function
IMG_WIDTH=224
IMG_HEIGHT=224
def decode_img(img):
  img = tf.image.decode_jpeg(img, channels=3)
  img = tf.image.convert_image_dtype(img, tf.float32) 
  img = tf.image.resize(img, [IMG_WIDTH, IMG_HEIGHT]) 
  img = tf.image.random_flip_left_right(img)
  img = tf.image.random_flip_up_down(img)
  img = tf.image.random_brightness(img, 0.3)
  return img

def get_label(path):
  part_list = tf.strings.split(path, os.path.sep)
  return part_list[-2]

def process_path(file_path):
  img = tf.io.read_file(file_path)
  img = decode_img(img)
  label = get_label(file_path)
  return img, label

In [69]:
AUTOTUNE = tf.data.experimental.AUTOTUNE
num_threads = 5 
train_ds = list_ds.map(process_path, num_parallel_calls=AUTOTUNE)

for image, label in train_ds.take(1):
  print("Image shape: ", image.numpy().shape)
  print("Label: ", label.numpy())

Image shape:  (224, 224, 3)
Label:  b'swift'


In [70]:

train_ds = train_ds.cache()
train_ds = train_ds.shuffle(10000)
train_ds = train_ds.repeat(23)
train_ds = train_ds.batch(128)
train_ds = train_ds.prefetch(tf.data.experimental.AUTOTUNE)

In [71]:
for image, label in train_ds:
  print("Image shape: ", label)


Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagon

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagon

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wago

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'w

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' 

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wa

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr'

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b's

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'

 b'swift'], shape=(128,), dtype=string)
Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' 

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' 

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'w

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift'

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swi

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'sw

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swi

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'w

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' 

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wa

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wago

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swif

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wa

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'w

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swi

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagon

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'w

Image shape:  tf.Tensor(
[b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'w

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 

Image shape:  tf.Tensor(
[b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' 

Image shape:  tf.Tensor(
[b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b

Image shape:  tf.Tensor(
[b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr

Image shape:  tf.Tensor(
[b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'swift' b'wagonr'
 b'wagonr' b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift'
 b'wagonr' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b's

In [72]:
ds = train_ds.take(1)

In [79]:
list(ds.as_numpy_iterator())

[(array([[[[ 0.788908  ,  0.73400605,  0.68302566],
           [ 0.7933899 ,  0.73848796,  0.68750757],
           [ 0.7796644 ,  0.72476244,  0.6737821 ],
           ...,
           [ 0.7642581 ,  0.728964  ,  0.6701405 ],
           [ 0.77378196,  0.7411489 ,  0.68764746],
           [ 0.7833057 ,  0.75193316,  0.70095277]],
  
          [[ 0.788908  ,  0.73400605,  0.68302566],
           [ 0.7933899 ,  0.73848796,  0.68750757],
           [ 0.7796644 ,  0.72476244,  0.6737821 ],
           ...,
           [ 0.7676545 ,  0.73236036,  0.6698979 ],
           [ 0.7748736 ,  0.7399359 ,  0.68182516],
           [ 0.7833057 ,  0.7455043 ,  0.6968286 ]],
  
          [[ 0.788908  ,  0.73400605,  0.68302566],
           [ 0.7933899 ,  0.73848796,  0.68750757],
           [ 0.7796644 ,  0.72476244,  0.6737821 ],
           ...,
           [ 0.77427214,  0.7298393 ,  0.66986036],
           [ 0.7811349 ,  0.7367021 ,  0.6809248 ],
           [ 0.7866784 ,  0.74146396,  0.6880313 ]],
  
    

In [78]:
for image,label in ds:  # example is `{'image': tf.Tensor, 'label': tf.Tensor}`
  print(image.shape, label)

(128, 224, 224, 3) tf.Tensor(
[b'wagonr' b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'wagonr' b'swift' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'swift' b'swift' b'swift' b'swift' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'swift' b'swift' b'swift'
 b'swift' b'wagonr' b'swift' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'swift' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'swift'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'swift'
 b'swift' b'swift' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr'
 b'wagonr' b'wagonr' b'wagonr' b'swift' b'wagonr' b'wagonr' b'wagonr'
 b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr' b'swift' b'wagonr'
 b'swift' b'wa